comsol_data:
  data_path: "./data_comsol/data/"
  output_path: "./data_comsol/data/numpy_data"
  sigmae: 100
  sigmao: 0 
  sigmag: 1000000
  
learning:
  trainset_path: "./data_comsol/data/numpy_data/train"
  valset_path: "./data_comsol/data/numpy_data/val"
  testset_path: "./data_comsol/data/numpy_data/test"
  batchsize: 1
  n_epochs: 10
  cheap: True
  
